README.md, omnigan/trainer.py, omnigan/utils.py, shared/defaults.yml, tests/test_comet.py, tests/test_utils.py
* `trainer.log_losses`
* `test_comet.py`
* add documentation in `README.md`
=> Log losses

Contributing.md, README.md, omnigan/blocks.py, omnigan/data.py, omnigan/discriminator.py, omnigan/generator.py, omnigan/losses.py, omnigan/trainer.py, omnigan/transforms.py, omnigan/utils.py, shared/defaults.yml, tests/run.py, tests/test_classifier.py, tests/test_comet.py, tests/test_dis.py, tests/test_gen.py, tests/test_losses.py, tests/test_trainer.py, tests/test_utils.py
* **Encoder**: Resnet-based Content Encoder from MUNIT
* image => 64 (=`encoder.dim`) channels with 1 conv layer, same size
* conv-based downsamplings (`encoder.n_downsample` times)
* resblocks (`encoder.n_res` blocks)
* **Decoders**: Resnet-based Decoders from MUNIT for all tasks but the translation
* resblocks projections (`decoder.n_res` blocks)
* Sequence of `nn.Upsampling > Conv2dBlock` (`decoder.n_upsample` times)
* should match `encoder.n_downsample`
* final conv to get a feature map with 1 (`h`, `d`, `w`), 3 (`a`) or 19 (`s`) channels
* **Translation decoder**: SPADEResnet-based Decoder inspired by MUNIT and SPADE
* Conditioning the translation by `SPADE([h, d, s, w])`
=> Generator architecture

omnigan/trainer.py, omnigan/utils.py, shared/defaults.yml, tests/test_comet.py
less python default loading, more yaml loading
=> add default references in yaml

README.md, experiment.py, omnigan/blocks.py, omnigan/classifier.py, omnigan/data.py, omnigan/discriminator.py, omnigan/generator.py, omnigan/losses.py, omnigan/norms.py, omnigan/optim.py, omnigan/strings.py, omnigan/trainer.py, omnigan/transforms.py, omnigan/tutils.py, omnigan/utils.py, shared/experiment/exp.sh, shared/experiment/exp_defaults.yaml, shared/experiment/exp_example.yaml, shared/experiment/template.sh, tests/run.py, tests/test_classifier.py, tests/test_data.py, tests/test_mega_depth.py, tests/test_trainer.py, tests/test_utils.py, train.py
Add experiment procedure. See readme.md/#experiments
=> Experiments

omnigan/trainer.py, shared/trainer/defaults.yaml, train.py
What do you guys think is better:
Having "resume" as an option in the config file, or as an argument to be specified from the command line (argparse)? 
Right now I'm using the former (config file) but it can be changed
=> Adding saving and loading functionality

omnigan/losses.py, tests/test_losses.py
Add ADVENT-related loss and test all losses we have except travelLoss which is deprecated
=> ADVENT loss

omnigan/trainer.py, tests/test_comet.py
Small branch to include the log of step-time on comet-ml during training.
=> Include step-time log in comet

omnigan/losses.py, omnigan/trainer.py
Small branch to remove set_losses() from Trainer class and add it as a pure function in losses.py.
=> Switch set_losses() to losses.py

omnigan/utils.py, shared/trainer/defaults.yaml
=> Default configs + TODOs

omnigan/data.py, omnigan/transforms.py, omnigan/tutils.py
Add depth auxiliary task. 
json files with depth have yet to be generated but this is functional
Raw input data : images 
Depth in dataloader item: tensor 
We read the input images with the pil_image_loader function to apply the same transforms over all inputs (the original image, seg, mask ) but then consider that depth map as a tensor.
=> add Depth head

eval.py
Short program to infer model on a folder of images
=> adding evaluation code

omnigan/blocks.py, omnigan/data.py, omnigan/discriminator.py, omnigan/encoder.py, omnigan/generator.py, omnigan/losses.py, omnigan/trainer.py, omnigan/tutils.py, shared/trainer/defaults.yaml, tests/test_data.py, tests/test_dis.py, tests/test_gen.py, tests/test_trainer.py
Bringing the painter into omnigan. The code runs right now, but I'm wondering what our logic should be for switching between masking and painting. Like, do we have a flag in the configs that determines which mode omnigan is in (masking mode vs. painting mode)? What do you guys think?
=> [WIP] Painter

omnigan/blocks.py, omnigan/data.py, omnigan/discriminator.py, omnigan/generator.py, omnigan/losses.py, omnigan/norms.py, omnigan/trainer.py, omnigan/transforms.py, shared/trainer/defaults.yaml, tests/test_dis.py
Adding mutli-scale discriminators, and feature-matching loss
=> Training with multiscale discrims and featmatch

omnigan/utils.py, tests/test_dis.py, tests/test_losses.py, tests/test_trainer.py
I fixed the first 3 tests:
test_losses.py:
Issue: line 42, there is no "s" in key. We should change it to "x" or "m"
test_trainer.py:
Issue:
there is no function named "freeze" anymore. I think we need to delete it.
there is no "get_representation_loss" anymore. It should be "get_masker_loss" now.
line 180, the trainer.losses["D"] is a dict now. 'dict' object has no attribute 'verbose'
test_dis.py:
Issue:
the rand image has 3 channels but advent discriminator need a 2 (number of class) channel one.
Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```
test_gen.py: (I didn't fix this yet.)
Traceback (most recent call last):
File "test_gen.py", line 120, in <module>
out2 = G.painter(z, image * mask)
File …
```
=> fix tests and fix other small things

omnigan/eval_metrics.py
just a few metrics for now: f1, iou and trimap metric
=> add first masker metrics

omnigan/data.py, omnigan/trainer.py, omnigan/transforms.py, shared/trainer/defaults.yaml, train.py
There are a few bugs in master right now, for example
- Config file written to output directory is empty
- Color channel being shuffled during dataloading or visualization
=> Fixing bugs in master

omnigan/utils.py, shared/trainer/defaults.yaml, utils_scripts/make_json_files.py
I modified the make_json_file function so that it can create a train and a validation json file based on a pourcentage of validation data that we want. And I added a util file that we can call directly from the command line with the arguments needed by the function.
=> Adding util file to generate the json files

shared/trainer/defaults.yaml
Let's modify defaults.yaml here real quick
=> Getting defaults config up to date

omnigan/data.py, omnigan/losses.py, omnigan/tutils.py, shared/trainer/defaults.yaml
Use images from MiDaS model output 
predict inverse depth
add gradient matching loss term
=> Update depth head

infer.py
Small PR to give the option to link to existing masks for painter inference. Previously, a masker model had to be specified
=> Supply existing masks to painter for inference

omnigan/blocks.py, omnigan/generator.py, omnigan/losses.py, omnigan/utils.py, sbatch.py, shared/trainer/defaults.yaml, train.py
Please check that depth is correctly implemented from MiDaS paper
=> change megadepth loss to MiDaS loss and change depth decoder

omnigan/losses.py, omnigan/trainer.py, shared/trainer/defaults.yaml, tests/test_losses.py
Merging the entropy losses into one class.
=> Merge minent losses

infer.py, omnigan/blocks.py, omnigan/discriminator.py, omnigan/generator.py, omnigan/losses.py, omnigan/trainer.py, omnigan/tutils.py, shared/trainer/defaults.yaml, tests/test_gen.py
implementation closer to the use_vae=False setting in the original SPADE repo
=> Single disc painter + no z sampling

omnigan/deeplabv3.py, omnigan/eval_metrics.py, omnigan/fire.py, omnigan/logger.py, omnigan/trainer.py, omnigan/tutils.py, shared/trainer/defaults.yaml
Add logging of wildfires to segmentation task
=> Amp + Log wildfires

apply_events.py, omnigan/trainer.py, omnigan/tutils.py, omnigan/utils.py, tpus.py
Applying all the events to images in a directory
```
cd <somewhere>
gsutil -m cp -R gs://vicc-ai-test-data/tests-v1 .
git clone git@github.com:cc-ai/omnigan.git
cd omnigan
git checkout apply-events
python apply_events.py -i ../tests-v1/images -r ../tests-v1/model -o ../tests-v1/outputs -t
```
⚠️ `gs://vicc-ai-test-data` is not public, you need read access.
=> Apply events

apply_events.py, omnigan/blocks.py, omnigan/deeplabv3.py, omnigan/generator.py, shared/trainer/defaults.yaml, test_trainer.py, tpus.py
from https://github.com/CoinCheung/DeepLab-v3-plus-cityscapes/blob/master/models/deeplabv3plus.py
=> v3+ update

omnigan/eval_metrics.py
change mIoU metric to replicate sklearn
=> Eval metric

omnigan/trainer.py, shared/trainer/events.yaml
Ended up making only  a minor modification, tested in a notebook but didn't have time to run the whole thing within climateGAN yet, if you can check this go ahead !
=> change smog color
